{% set name = "moto" %}
{% set version = "5.1.19" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a13423e402366b6affab07ed28e1df5f3fcc54ef68fc8d83dc9f824da7a4024e

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - moto_server = moto.server:main
    - moto_proxy = moto.proxy:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=40.6.0
  run:
    - python
    - boto3 >=1.9.201
    - botocore >=1.20.88,!=1.35.45,!=1.35.46
    - cryptography >=35.0.0
    - requests >=2.5
    - xmltodict
    - werkzeug >=0.5,!=2.2.0,!=2.2.1
    - python-dateutil >=2.1,<3.0.0
    - responses >=0.15.0,!=0.25.5
    - jinja2 >=2.10.1
  run_constrained:
    - aws-sam-translator <=1.103.0
    - docker >=2.5.1
    - joserfc >=0.9.0
    - pyyaml >=5.1
    - cfn-lint >=0.40.0,<=1.41.0
    - openapi-spec-validator >=0.5.0
    - pydantic <=2.12.4
    - pyparsing >=3.0.7
    - py-partiql-parser >=0.6.3
    - aws-xray-sdk !=0.96,>=0.93
    - flask !=2.2.0,!=2.2.1

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.applicationautoscaling
    - moto.appsync
    - moto.athena
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.budgets
    - moto.cloudformation
    - moto.cloudfront
    - moto.cloudwatch
    - moto.codecommit
    - moto.codepipeline
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.datasync
    - moto.dax
    - moto.dms
    - moto.dms
    - moto.ds
    - moto.dynamodb
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ec2instanceconnect
    - moto.ecr
    - moto.ecs
    - moto.efs
    - moto.eks
    - moto.elasticache
    - moto.elasticbeanstalk
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.emrcontainers
    - moto.es
    - moto.events
    - moto.firehose
    - moto.forecast
    - moto.glacier
    - moto.glue
    - moto.guardduty
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kinesisvideo
    - moto.kinesisvideoarchivedmedia
    - moto.kms
    - moto.logs
    - moto.managedblockchain
    - moto.mediaconnect
    - moto.medialive
    - moto.mediapackage
    - moto.mediastore
    - moto.mediastoredata
    - moto.organizations
    - moto.packages
    - moto.polly
    - moto.ram
    - moto.rds
    - moto.redshift
    - moto.resourcegroups
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.route53resolver
    - moto.s3
    - moto.s3bucket_path
    - moto.s3control
    - moto.sagemaker
    - moto.sdb
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.ssoadmin
    - moto.stepfunctions
    - moto.sts
    - moto.support
    - moto.swf
    - moto.swf.models
    - moto.timestreamwrite
    - moto.transcribe
    - moto.utilities
    - moto.wafv2
    - moto.xray
  requires:
    - pip
    - pyparsing
    - joserfc
    - flask
    - flask_cors
    - openapi-spec-validator
    - aws-xray-sdk
    - multipart
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - moto_server --help
    - moto_proxy --help

about:
  home: https://docs.getmoto.org
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library that allows your python tests to easily mock out the boto library.
  description: A library that allows you to easily mock out tests based on AWS infrastructure.
  doc_url: https://docs.getmoto.org
  dev_url: https://github.com/getmoto/moto

extra:
  recipe-maintainers:
    - jan-janssen
    - johanneskoester
    - mariusvniekerk
    - hajapy
  skip-lints:
    - missing_pip_check
