{% set version = "1.3.7" %}

package:
  name: moto
  version: {{ version }}

source:
  fn: moto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
  sha256: 129de2e04cb250d9f8b2c722ec152ed1b5426ef179b4ebb03e9ec36e6eb3fcc5

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.7.3
    - boto >=2.36.0
    - botocore >=1.12.13
    - boto3 >=1.6.15
    - cookies
    - requests >=2.5
    - xmltodict
    - dicttoxml
    - six
    - werkzeug
    - pyaml
    - pytz
    - python-dateutil
    - mock
    - flask
    - responses >=0.9.0
    - python-jose <3.0.0
    - aws-xray-sdk !=0.96,>=0.93
    - jsondiff 1.1.1
    - docker-py
    - backports.tempfile

test:
  imports:
    - moto

  commands:
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
