{% set version = "4.0.8" %}

package:
  name: moto
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
    sha256: 3bd8a72dc385819c84ed3f9d18c386985634041c6ae544d957bd8ab88c6c15f1
  - url: https://github.com/spulec/moto/archive/{{ version }}.tar.gz
    sha256: ec87415a70d3e0464e9d79700f090b77e26b65e5c341ba579dedaaa9844f571f
    folder: github

build:
  number: 0
  # there seem to be missing docker-py >=2.5.1 and cfn-lint >=0.4.0 for s390x
  skip: True  # [py<37]
  entry_points:
    - moto_server = moto.server:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - jinja2 >=2.10.1
    # we need to bound this since 198 changed some of the api
    - boto3 >=1.9.201
    - botocore >=1.12.201
    - cryptography >=3.3.1
    - requests >=2.5
    - xmltodict
    - werkzeug >=0.5,!=2.2.0,!=2.2.1
    - pytz
    - python-dateutil >=2.1,<3.0.0
    - responses >=0.13.0
    - markupsafe !=2.0.0a1
    - importlib_metadata # [py<38]
    - pyyaml >=5.1
    - python-jose >=3.1.0,<4.0.0
    - ecdsa !=0.15
    - dataclasses # [py<37]
    - docker-py >=2.5.1
    - jsondiff >=1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - idna >=2.5,<4
    - cfn-lint >=0.4.0
    - sshpubkeys >=3.1.0
    - openapi-spec-validator >=0.2.8
    - pyparsing >=3.0.7
    - flask !=2.2.0,!=2.2.1
    - flask_cors

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.cloudformation
    - moto.cloudwatch
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.dynamodb
    - moto.dynamodb_v20111205
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ecr
    - moto.ecs
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.events
    - moto.glacier
    - moto.glue
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kms
    - moto.logs
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.polly
    - moto.rds
    - moto.redshift
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.s3
    - moto.s3bucket_path
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.sts
    - moto.swf
    - moto.swf.models
    - moto.xray
  requires:
    - nose
    - nose-exclude
    - pytest
    - pluggy <1.0.0
    - pip
    - python <3.10
    - freezegun
    - parameterized
    # needed for passing pip check
    - rsa
    - pyasn1
  source_files:
    - github/tests
  commands:
    - pip check
    - moto_server --help
    - pip install sure
    - cd github
#     - >
#       pytest tests --verbose
#         -k "not test_lambda"
#         -k "not test_batch"
#         -k "not test_lambda_cloudformation"
#         -k "not test_cognitoidp.test_token_legitimacy"
#         -k "not test_create_stack_lambda_and_dynamodb"
#         -k "not tests.test_cloudformation.test_validate"
#         -k "not test_cloudformation_stack_integration.test_lambda_function"

about:
  home: http://docs.getmoto.org/en/latest/#
  description : A library that allows you to easily mock out tests based on AWS infrastructure.
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  license_url: https://github.com/spulec/moto/blob/{{ version }}/LICENSE
  doc_url: http://docs.getmoto.org
  doc_source_url: https://github.com/spulec/moto/tree/{{ version }}/docs
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
    - hajapy
