{% set version = "1.3.8" %}

package:
  name: moto
  version: {{ version }}

source:
  fn: moto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
  sha256: 9cb02134148fbe3ed81f11d6ab9bd71bbd6bc2db7e59a45de77fb1d0fedb744e

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.10.1
    - boto >=2.36.0
    - boto3 >=1.9.86
    - botocore >=1.12.86
    - cryptography >=2.3.0
    - requests >=2.5
    - xmltodict
    - six >1.9
    - werkzeug
    - pyyaml
    - pytz
    - python-dateutil >=2.1,<3.0.0
    - python-jose <4.0.0
    - mock
    - docker-py >=2.5.1
    - jsondiff 1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - responses >=0.9.0
    - idn >=2.5,<2.9
    - cfn-lint
    - flask

test:
  imports:
    - moto

  commands:
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
    - hajapy
