{% set version = "5.1.12" %}

package:
  name: moto
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/m/moto/moto-{{ version }}.tar.gz
    sha256: 6eca3a020cb89c188b763610c27c969c32b832205712d3bdcb1a6031a4005187

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - moto_server = moto.server:main
    - moto_proxy = moto.proxy:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=40.6.0
  run:
    - python
    - boto3 >=1.9.201
    - botocore >=1.20.88,!=1.35.45,!=1.35.46
    - cryptography >=35.0.0
    - requests >=2.5
    - xmltodict
    - werkzeug >=0.5,!=2.2.0,!=2.2.1
    - python-dateutil <3.0.0,>=2.1
    - responses >=0.15.0,!=0.25.5
    - jinja2 >=2.10.1
    - docker-py >=3.0.0
    - graphql-core
    - pyyaml >=5.1
    - cfn-lint >=0.40.0
    - flask !=2.2.0,!=2.2.1
    - flask_cors
    - jsondiff >=1.1.2
    - aws-xray-sdk >=0.93,!=0.96
    - openapi-spec-validator >=0.5.0
    - joserfc >=0.9.0
    - antlr4-python3-runtime
    - pyparsing >=3.0.7
    - jsonpath-ng
    - py-partiql-parser 0.5.4
    - multipart
  run_constrained:
    - PyYAML >=5.1
    - openapi-spec-validator >=0.5.0
    - joserfc >=0.9.0
    - docker-py >=2.5.1
    - py-partiql-parser ==0.6.1
    - pyparsing >=3.0.7
    - cfn-lint >=0.40.0
    - aws-xray-sdk !=0.96,>=0.93
    - flask !=2.2.0,!=2.2.1

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.applicationautoscaling
    - moto.appsync
    - moto.athena
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.budgets
    - moto.cloudformation
    - moto.cloudfront
    - moto.cloudwatch
    - moto.codecommit
    - moto.codepipeline
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.datasync
    - moto.dax
    - moto.dms
    - moto.dms
    - moto.ds
    - moto.dynamodb
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ec2instanceconnect
    - moto.ecr
    - moto.ecs
    - moto.efs
    - moto.eks
    - moto.elasticache
    - moto.elasticbeanstalk
    - moto.elastictranscoder
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.emrcontainers
    - moto.es
    - moto.events
    - moto.firehose
    - moto.forecast
    - moto.glacier
    - moto.glue
    - moto.guardduty
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kinesisvideo
    - moto.kinesisvideoarchivedmedia
    - moto.kms
    - moto.logs
    - moto.managedblockchain
    - moto.mediaconnect
    - moto.medialive
    - moto.mediapackage
    - moto.mediastore
    - moto.mediastoredata
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.polly
    - moto.ram
    - moto.rds
    - moto.redshift
    - moto.resourcegroups
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.route53resolver
    - moto.s3
    - moto.s3bucket_path
    - moto.s3control
    - moto.sagemaker
    - moto.sdb
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.ssoadmin
    - moto.stepfunctions
    - moto.sts
    - moto.support
    - moto.swf
    - moto.swf.models
    - moto.timestreamwrite
    - moto.transcribe
    - moto.utilities
    - moto.wafv2
    - moto.xray
  requires:
    - pip
  commands:
    # pip check fails on docker-py for windows
    - pip check  # [not win]
    - moto_server --help

about:
  home: https://docs.getmoto.org/en/latest/#
  description: A library that allows you to easily mock out tests based on AWS infrastructure.
  summary: A library that allows your python tests to easily mock out the boto library.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://docs.getmoto.org
  dev_url: https://github.com/getmoto/moto

extra:
  recipe-maintainers:
    - jan-janssen
    - johanneskoester
    - mariusvniekerk
    - hajapy
  skip-lints:
    - missing_pip_check
