{% set version = "1.3.4" %}

package:
  name: moto
  version: {{ version }}

source:
  fn: moto-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
  sha256: 7c86d1c3bd6362954afaded735354c11afd22037eb6736152f057a1bff0c8868

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2 >=2.8
    - boto >=2.36.0
    - botocore <1.11
    - boto3 >=1.2.1,<1.8.0
    - cookies
    - requests >=2.0
    - xmltodict
    - dicttoxml
    - six
    - werkzeug
    - pyaml
    - pytz
    - python-dateutil
    - mock
    - flask
    - responses >=0.9.0
    - python-jose <3.0.0
    - docker-py

test:
  imports:
    - moto

  commands:
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
