import moto
import moto.acm
import moto.apigateway
import moto.applicationautoscaling
import moto.appsync
import moto.athena
import moto.autoscaling
import moto.awslambda
import moto.batch
import moto.budgets
import moto.cloudformation
import moto.cloudfront
import moto.cloudwatch
import moto.codecommit
import moto.codepipeline
import moto.cognitoidentity
import moto.cognitoidp
import moto.config
import moto.core
import moto.datapipeline
import moto.datasync
import moto.dax
import moto.dms
import moto.ds
import moto.dynamodb
import moto.dynamodbstreams
import moto.ec2
import moto.ec2.responses
import moto.ec2instanceconnect
import moto.ecr
import moto.ecs
import moto.efs
import moto.eks
import moto.elasticache
import moto.elasticbeanstalk
import moto.elb
import moto.elbv2
import moto.emr
import moto.emrcontainers
import moto.es
import moto.events
import moto.firehose
import moto.forecast
import moto.glacier
import moto.glue
import moto.guardduty
import moto.iam
import moto.instance_metadata
import moto.iot
import moto.iotdata
import moto.kinesis
import moto.kinesisvideo
import moto.kinesisvideoarchivedmedia
import moto.kms
import moto.logs
import moto.managedblockchain
import moto.mediaconnect
import moto.medialive
import moto.mediapackage
import moto.mediastore
import moto.mediastoredata
import moto.organizations
import moto.packages
import moto.polly
import moto.ram
import moto.rds
import moto.redshift
import moto.resourcegroups
import moto.resourcegroupstaggingapi
import moto.route53
import moto.route53resolver
import moto.s3
import moto.s3bucket_path
import moto.s3control
import moto.sagemaker
import moto.sdb
import moto.secretsmanager
import moto.ses
import moto.sns
import moto.sqs
import moto.ssm
import moto.ssoadmin
import moto.stepfunctions
import moto.sts
import moto.support
import moto.swf
import moto.swf.models
import moto.timestreamwrite
import moto.transcribe
import moto.utilities
import moto.wafv2
import moto.xray
