travis:
  secure:
    BINSTAR_TOKEN: tjX+/KI2yTLguERmUq9+OXFH7o+XKWokQ7Y13o++LM0lqEr04OG1RpLs2zV3b/t2BgxUa6Z219pvqduZ9BL50AkjE8aIvWIqh7NIu7U3ZLpmpmy6hsGZXEjNl0Y8wzruzzSusX2sdUtOZ3roAOjyixIDm4e9mlLw/IgKW4hlha0Dhy5bHNa8EGlYbAmqDzSg9qnvcpcakQnYlBtdmV7CB8GsKs28YHk+BUZrYU8z6S6w/RRqLebJD6Bmb5K1jXG03KZ9j4RisoDewrGY8P+zBmeygkU31cu5pH0f2fLXnetC43qjhJvgfZwHtU5WOrNwwuh87KKK5A9jrA6OFndJFC29cVXdBR5/POpc/BR7lKlJZs2sodpIkCFJvkbjOMFnYa1CYlpHE80IEyCMN10b0sNmpymHk0KFRZ6UDtzCC/vL7AczV6z8ufgPSoOai1+5BXxcQbCMW9mPd55KTNdlnIgmLYEtR1wPWkM7TaXCAVROhX7iF4COngt6ARkSYis0mQpJvdfRWhwvwlPde26u8s1EM6n+F0rn9HLObsaPC9QZ6U6kob3oTIZ5+T6g5wUtVBmAsXHSozMMZeEiA/bk3iHZrJYelFIB/rwQ8bHffFXwAbck3eMI3A0XxdLu70ZbJz5hdGY5LnpmgPsxZZ6chu6fQC7+jA7KgvT4y4A5FoA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
