travis:
  secure:
    BINSTAR_TOKEN: Z/Cx/9NxxFgHsqONxLfBw7rwKdfuwyw+qQXgdFIUJdQ+66OmCI6cHswHs1zjtCGSjo6Bpv0KmaC7wfvjWT4yPdq9gzV1liOMaS9iJwV8WKWyL0xFJdxt848TkPpwq+Dgi0FVdcfGWpFGYRJDV651XPg7ptIvC3vQtp9DMwoRR5Tzt3koM4cdIXAwBMv208BBSc9oVxk1NTzOsURZCa1wES9wvuoVNx/Jn/ZjMEgMIYayJJkvtGFitNQeX3aMa1zB5c+8po23FPfn1ujCdDu1FFCmV9QxO4Q2Jkz/9ZBltW8ZZSMOrVEHv3+e6qE/lRTFG50DDUBGWUmnv7UZNJ0kAuUqZRKjFd1criuFJ8jEPHhYOlfuKUICBMhqAM8Kf57B9lSf9z+XpvQxFqYZ3QAio2udmhY73hr/YZcK7ala8BgGBGN09Hs+fD5PhM9lG8+XsEIn4kfXlVN+wz5MmgE+18dK9AGyPfMnbSDIiOUHhnNj2ScOFUoXDl+p/9RfGLxeteEitqEZaBvGzCGnYibqmuevoTkxBPj9dKOouAeJEWyIvf4Elu1kJ3A34gOIrYkMq2hjbLPlGUOxS7bB4JmdDGhJPu2LELKMhpgax6iAdSkOUS541T62oKEm3Cx/RHDHUu6yn7311mqwCmKzDnUSfZZqfTyi2HChEJ72OFt6sZk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
